"""Classify exact content repeated within repositories containing CLAUDE.md.

The analysis unit is first a unique SHA-256 content identity, classified once,
and then each repository-local duplicate group.  Results are aggregated by
unique content, repository group, participating file, repeated instance, and
repository.  SQLite is opened read-only and immutable.

Example:

    python scripts/claude_repeated_content_classes.py \\
        --db mined.db \\
        --classes-output article/claude_repeated_content_classes.csv \\
        --groups-output article/claude_repeated_content_groups.csv \\
        --members-output article/claude_repeated_content_members.csv \\
        --audit-output article/claude_repeated_content_audit.csv \\
        --summary-output article/claude_repeated_content_summary.json
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import re
import sqlite3
import sys
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path, PurePosixPath
from typing import Iterable, Sequence


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from miner.markdown_references import (  # noqa: E402
    MarkdownReference,
    extract_local_markdown_references,
    iter_unfenced_lines,
)


CATEGORIES = (
    "pointer_shim",
    "empty_placeholder",
    "generated_context",
    "template_scaffold",
    "substantive_repeated_document",
    "short_ambiguous",
)
WORD_RE = re.compile(r"[\w]+(?:[-'][\w]+)*", re.UNICODE)
HEADING_RE = re.compile(r"^[ ]{0,3}#{1,6}[ \t]+(?P<text>.*?)[ \t]*#*[ \t]*$")
HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
EMPTY_TAG_PAIR_RE = re.compile(
    r"<(?P<tag>[A-Za-z][\w:.-]*)(?:\s[^>]*)?>\s*</(?P=tag)>",
    re.DOTALL | re.IGNORECASE,
)
POINTER_CUE_RE = re.compile(
    r"\b(?:instruction|instructions|read|refer|follow|use|uses|using|load|loads|"
    r"import(?:s|ed|ing)?|source of truth|guidance|see)\b",
    re.IGNORECASE,
)
LEGACY_RULES_POINTER_RE = re.compile(
    r"^[ \t]*@?(?P<target>(?:\.{1,2}/)*\.?rules)[ \t]*$",
    re.IGNORECASE,
)
GENERIC_AT_POINTER_RE = re.compile(
    r"^[ \t]*@(?P<target>(?:\.{1,2}/|/)?[^\s<>`]+)[ \t]*$",
    re.IGNORECASE,
)
GENERATED_PATTERNS = (
    ("claude_mem_context", re.compile(r"<claude-mem-context\b", re.IGNORECASE)),
    (
        "explicit_generated_header",
        re.compile(
            r"(?:\A|\n)[ \t]*(?:<!--\s*)?(?:this file is[ \t]+)?"
            r"(?:auto[- ]?generated|automatically generated|generated by)\b",
            re.IGNORECASE,
        ),
    ),
    (
        "do_not_edit_generated_file",
        re.compile(r"\bdo not edit (?:this )?(?:generated )?file\b", re.IGNORECASE),
    ),
    (
        "generated_context_marker",
        re.compile(r"\b(?:generated|session|memory) context\b", re.IGNORECASE),
    ),
)
TEMPLATE_PATTERNS = (
    (
        "self_declared_template",
        re.compile(
            r"\bthis (?:file|document|project|repository|repo) is (?:an? )?"
            r"(?:template|scaffold|starter)\b",
            re.IGNORECASE,
        ),
    ),
    (
        "template_for",
        re.compile(
            r"\b(?:[A-Za-z0-9_-]+|this (?:project|repository)) is (?:an? )?"
            r"(?:[A-Za-z0-9+#.-]+ )?(?:template|scaffold) for\b",
            re.IGNORECASE,
        ),
    ),
    (
        "clone_and_customize",
        re.compile(
            r"\bmeant to be (?:cloned|copied)(?: and|, then)? customi[sz]ed\b",
            re.IGNORECASE,
        ),
    ),
    (
        "explicit_scaffold",
        re.compile(r"\bthis is (?:an? )?(?:project )?scaffold\b", re.IGNORECASE),
    ),
)
GENERIC_HEADINGS = {
    "claude",
    "claude.md",
    "claude code",
    "claude code instructions",
    "instructions",
    "instructions for claude",
    "project instructions",
}
PLACEHOLDER_PHRASES = {
    "todo",
    "tbd",
    "placeholder",
    "coming soon",
    "n/a",
    "none",
    "empty",
}
PATH_CONTEXT_MARKERS = {
    "benchmark_or_run": {
        "benchmark",
        "benchmarks",
        "eval",
        "evals",
        "evaluation",
        "evaluations",
        "fixture",
        "fixtures",
        "run",
        "runs",
    },
    "template_or_example": {
        "example",
        "examples",
        "sample",
        "samples",
        "scaffold",
        "scaffolds",
        "starter",
        "starters",
        "template",
        "templates",
    },
    "mirror_or_vendor": {
        "mirror",
        "mirrors",
        "third_party",
        "vendor",
        "vendored",
    },
    "skill_plugin_or_agent": {
        "agent",
        "agents",
        "plugin",
        "plugins",
        "skill",
        "skills",
    },
    "package_app_or_component": {
        "app",
        "apps",
        "component",
        "components",
        "connector",
        "connectors",
        "crate",
        "crates",
        "package",
        "packages",
        "service",
        "services",
    },
}


@dataclass(frozen=True)
class ClassifierConfig:
    pointer_max_residual_words: int = 60
    substantive_min_words: int = 50
    substantive_min_nonempty_lines: int = 8
    substantive_min_bytes: int = 500


@dataclass(frozen=True)
class DuplicateMember:
    repo_full_name: str
    content_hash: str
    path: str
    size_bytes: int | None
    html_url: str | None


@dataclass(frozen=True)
class BaseClassification:
    content_hash: str
    size_bytes: int | None
    line_count: int
    nonempty_line_count: int
    word_count: int
    heading_count: int
    reference_count: int
    direct_include_count: int
    target_category: str
    target_basenames: str
    target_paths: str
    primary_category: str
    subtype: str
    confidence: str
    rule_id: str
    evidence: str
    content_excerpt: str


@dataclass(frozen=True)
class ContentClassRow:
    content_hash: str
    repository_groups: int
    repositories: int
    files: int
    repeated_instances: int
    size_bytes: int | None
    line_count: int
    nonempty_line_count: int
    word_count: int
    heading_count: int
    reference_count: int
    direct_include_count: int
    primary_category: str
    subtype: str
    confidence: str
    rule_id: str
    target_category: str
    target_basenames: str
    target_paths: str
    representative_repo: str
    representative_path: str
    evidence: str
    content_excerpt: str


@dataclass(frozen=True)
class GroupRow:
    repo_full_name: str
    content_hash: str
    copies: int
    repeated_instances: int
    size_bytes: int | None
    primary_category: str
    subtype: str
    confidence: str
    rule_id: str
    target_category: str
    target_basenames: str
    target_paths: str
    path_context_tags: str
    representative_path: str
    evidence: str


@dataclass(frozen=True)
class MemberRow:
    repo_full_name: str
    content_hash: str
    group_copies: int
    group_repeated_instances: int
    primary_category: str
    subtype: str
    path_context_tags: str
    path: str
    size_bytes: int | None
    html_url: str | None


@dataclass(frozen=True)
class AuditRow:
    audit_id: str
    category_stratum: str
    size_band: str
    content_hash: str
    repository_groups: int
    files: int
    repeated_instances: int
    size_bytes: int | None
    representative_repo: str
    representative_path: str
    auto_category: str
    auto_subtype: str
    auto_confidence: str
    rule_id: str
    target_basenames: str
    evidence: str
    content_excerpt: str
    review_category: str = ""
    review_correct: str = ""
    review_notes: str = ""


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def _exact_predicate(*, alias: str = "") -> str:
    prefix = f"{alias}." if alias else ""
    return (
        f"(lower({prefix}path) = 'claude.md' "
        f"OR lower({prefix}path) LIKE '%/claude.md')"
    )


def _readonly_connection(db_path: str | Path) -> sqlite3.Connection:
    path = Path(db_path)
    if not path.is_file():
        raise FileNotFoundError(f"database not found: {path}")
    connection = sqlite3.connect(
        path.resolve().as_uri() + "?mode=ro&immutable=1",
        uri=True,
        timeout=30,
    )
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA query_only=ON")
    return connection


def _share(numerator: int, denominator: int) -> float:
    return numerator / denominator if denominator else 0.0


def _size_band(size_bytes: int | None) -> str:
    if size_bytes is None:
        return "unknown"
    if size_bytes <= 50:
        return "<=50"
    if size_bytes <= 200:
        return "51-200"
    if size_bytes <= 1000:
        return "201-1000"
    if size_bytes <= 5000:
        return "1001-5000"
    return ">5000"


def _excerpt(content: str, limit: int = 600) -> str:
    text = content[:limit].replace("\r", "\\r").replace("\n", "\\n")
    if len(content) > limit:
        text += "…"
    return text


def _evidence_line(content: str, match: re.Match[str], limit: int = 220) -> str:
    start = content.rfind("\n", 0, match.start()) + 1
    end = content.find("\n", match.end())
    if end < 0:
        end = len(content)
    return _excerpt(content[start:end].strip(), limit)


def _normalized_heading(line: str) -> str | None:
    match = HEADING_RE.match(line)
    if match is None:
        return None
    text = re.sub(r"[`*_~]", "", match.group("text")).strip().casefold()
    return text


def _remove_generic_headings_and_comments(content: str) -> str:
    text = HTML_COMMENT_RE.sub("", content)
    retained: list[str] = []
    for line in text.splitlines():
        heading = _normalized_heading(line)
        if heading in GENERIC_HEADINGS:
            continue
        retained.append(line)
    return "\n".join(retained)


def _yaml_front_matter_lines(content: str) -> set[int]:
    lines = content.splitlines()
    if not lines or lines[0].strip() != "---":
        return set()
    for index, line in enumerate(lines[1:], 2):
        if line.strip() in {"---", "..."}:
            return set(range(1, index + 1))
    return set()


def _placeholder_subtype(content: str) -> tuple[str, str] | None:
    residual = _remove_generic_headings_and_comments(content).strip()
    if not residual or not re.search(r"[\w]", residual, re.UNICODE):
        return "empty_or_punctuation", "no substantive characters after titles/comments"

    without_tags = residual
    empty_tags: list[str] = []
    while True:
        match = EMPTY_TAG_PAIR_RE.search(without_tags)
        if match is None:
            break
        empty_tags.append(match.group("tag"))
        without_tags = without_tags[: match.start()] + without_tags[match.end() :]
    if empty_tags and not re.search(r"[\w]", without_tags, re.UNICODE):
        subtype = (
            "empty_generated_block"
            if any("claude" in tag.casefold() or "context" in tag.casefold() for tag in empty_tags)
            else "empty_tag_block"
        )
        return subtype, f"empty paired tag(s): {', '.join(empty_tags[:3])}"

    normalized = re.sub(r"[^\w]+", " ", residual, flags=re.UNICODE).strip().casefold()
    if normalized in PLACEHOLDER_PHRASES:
        return "placeholder_phrase", f"placeholder text: {normalized}"

    body_without_headings = "\n".join(
        line for line in residual.splitlines() if _normalized_heading(line) is None
    )
    body_words = {
        word.casefold() for word in WORD_RE.findall(body_without_headings)
    }
    empty_section_words = {
        "a",
        "info",
        "issue",
        "issues",
        "n",
        "no",
        "none",
        "note",
        "notes",
        "warning",
        "warnings",
    }
    if body_words and body_words <= empty_section_words:
        return "empty_sections", "section bodies contain only empty-status words"
    return None


def _reference_summary(
    references: Sequence[MarkdownReference],
) -> tuple[str, str, str]:
    paths = sorted({reference.normalized_target for reference in references}, key=str.casefold)
    basenames = sorted({reference.target_basename for reference in references})
    target_kinds = set()
    for basename in basenames:
        if basename == "agents.md":
            target_kinds.add("agents_md")
        elif "rule" in basename:
            target_kinds.add("rules_md")
        elif basename == "claude.md":
            target_kinds.add("claude_md")
        else:
            target_kinds.add("other_md")
    target_category = (
        next(iter(target_kinds)) if len(target_kinds) == 1 else "mixed_md"
    ) if target_kinds else "none"
    return target_category, ";".join(basenames), ";".join(paths)


def _pointer_classification(
    content: str,
    references: Sequence[MarkdownReference],
    *,
    maximum_residual_words: int,
) -> tuple[str, str, str] | None:
    if not references or "```" in content or "~~~" in content:
        return None
    explicit_lines = {
        reference.line_number
        for reference in references
        if reference.syntax in {"direct_include", "comment_include"}
    }
    references_by_line: dict[int, list[MarkdownReference]] = defaultdict(list)
    for reference in references:
        references_by_line[reference.line_number].append(reference)
    residual_lines: list[str] = []
    front_matter_lines = _yaml_front_matter_lines(content)
    for line_number, line in iter_unfenced_lines(content):
        if (
            line_number in explicit_lines
            or line_number in front_matter_lines
            or not line.strip()
        ):
            continue
        if _normalized_heading(line) is not None:
            continue
        cleaned = line
        for reference in references_by_line.get(line_number, []):
            cleaned = cleaned.replace(reference.raw_target, "")
        if WORD_RE.search(cleaned):
            residual_lines.append(cleaned)
    residual = HTML_COMMENT_RE.sub("", "\n".join(residual_lines)).strip()
    residual_words = len(WORD_RE.findall(residual))
    explicit = len(explicit_lines)
    evidence = "; ".join(
        f"{reference.syntax}:{reference.normalized_target}"
        for reference in references[:3]
    )
    if explicit and residual_words == 0:
        subtype = (
            "direct_include_only"
            if any(reference.syntax == "direct_include" for reference in references)
            else "comment_include_only"
        )
        return subtype, "high", evidence
    if not explicit and residual_words == 0:
        return "path_only", "high", evidence
    if (
        explicit
        and residual_words <= maximum_residual_words
        and POINTER_CUE_RE.search(residual)
    ):
        return "direct_include_with_explanation", "high", evidence
    if (
        not explicit
        and residual_words <= min(maximum_residual_words, 50)
        and POINTER_CUE_RE.search(residual)
    ):
        return "prose_pointer", "medium", evidence
    return None


def classify_content(
    content_hash: str,
    content: str,
    size_bytes: int | None,
    *,
    config: ClassifierConfig = ClassifierConfig(),
) -> BaseClassification:
    """Assign one exclusive, evidence-bearing form category."""
    lines = content.splitlines()
    nonempty = [line for line in lines if line.strip()]
    words = WORD_RE.findall(content)
    headings = [line for line in lines if _normalized_heading(line) is not None]
    references = extract_local_markdown_references(content)
    target_category, target_basenames, target_paths = _reference_summary(references)
    direct_count = sum(reference.syntax == "direct_include" for reference in references)

    pointer = _pointer_classification(
        content,
        references,
        maximum_residual_words=config.pointer_max_residual_words,
    )
    placeholder = _placeholder_subtype(content)
    legacy_text = _remove_generic_headings_and_comments(content).strip()
    legacy_match = LEGACY_RULES_POINTER_RE.fullmatch(legacy_text)
    generic_at_match = GENERIC_AT_POINTER_RE.fullmatch(legacy_text)
    generated_match = next(
        (
            (subtype_name, pattern.search(content[:1500]))
            for subtype_name, pattern in GENERATED_PATTERNS
            if pattern.search(content[:1500]) is not None
        ),
        None,
    )
    template_match = next(
        (
            (subtype_name, pattern.search(content[:2000]))
            for subtype_name, pattern in TEMPLATE_PATTERNS
            if pattern.search(content[:2000]) is not None
        ),
        None,
    )

    if pointer is not None:
        category = "pointer_shim"
        subtype, confidence, evidence = pointer
        rule_id = "pointer_form_v1"
    elif placeholder is not None:
        category = "empty_placeholder"
        subtype, evidence = placeholder
        confidence = "high"
        rule_id = "placeholder_form_v1"
    elif legacy_match is not None:
        category = "pointer_shim"
        subtype = "legacy_rules_pointer"
        confidence = "high"
        rule_id = "legacy_rules_pointer_v1"
        legacy_target = legacy_match.group("target")
        target_category = "rules_file"
        target_basenames = PurePosixPath(legacy_target).name.casefold()
        target_paths = legacy_target
        evidence = f"legacy_rules_pointer:{legacy_target}"
    elif generic_at_match is not None:
        category = "pointer_shim"
        subtype = "generic_at_pointer"
        confidence = "high"
        rule_id = "generic_at_pointer_v1"
        generic_target = generic_at_match.group("target")
        target_category = "other_path"
        target_basenames = PurePosixPath(generic_target).name.casefold()
        target_paths = generic_target
        evidence = f"generic_at_pointer:{generic_target}"
    elif generated_match is not None:
        category = "generated_context"
        subtype = generated_match[0]
        confidence = "high"
        rule_id = "generated_marker_v1"
        assert generated_match[1] is not None
        evidence = _evidence_line(content, generated_match[1])
    elif template_match is not None:
        category = "template_scaffold"
        subtype = template_match[0]
        confidence = "high"
        rule_id = "explicit_template_marker_v1"
        assert template_match[1] is not None
        evidence = _evidence_line(content, template_match[1])
    elif (
        len(words) >= config.substantive_min_words
        or len(nonempty) >= config.substantive_min_nonempty_lines
        or (size_bytes or 0) >= config.substantive_min_bytes
    ):
        category = "substantive_repeated_document"
        subtype = "size_or_structure_threshold"
        confidence = "high"
        rule_id = "substantive_form_v1"
        evidence = (
            f"words={len(words)}; nonempty_lines={len(nonempty)}; "
            f"bytes={size_bytes if size_bytes is not None else 'unknown'}"
        )
    else:
        category = "short_ambiguous"
        subtype = "no_high_precision_form_rule"
        confidence = "low"
        rule_id = "fallback_v1"
        evidence = (
            f"words={len(words)}; nonempty_lines={len(nonempty)}; "
            f"references={len(references)}"
        )

    return BaseClassification(
        content_hash=content_hash,
        size_bytes=size_bytes,
        line_count=len(lines),
        nonempty_line_count=len(nonempty),
        word_count=len(words),
        heading_count=len(headings),
        reference_count=len(references),
        direct_include_count=direct_count,
        target_category=target_category,
        target_basenames=target_basenames,
        target_paths=target_paths,
        primary_category=category,
        subtype=subtype,
        confidence=confidence,
        rule_id=rule_id,
        evidence=evidence,
        content_excerpt=_excerpt(content),
    )


def _path_context_tags(paths: Iterable[str]) -> str:
    components = {
        part.casefold()
        for path in paths
        for part in PurePosixPath(path).parts[:-1]
    }
    tags = [
        tag
        for tag, markers in PATH_CONTEXT_MARKERS.items()
        if components & markers
    ]
    return ";".join(tags)


def _group_query() -> str:
    predicate = _exact_predicate()
    aliased = _exact_predicate(alias="f")
    return f"""
        WITH duplicate_groups AS (
            SELECT repo_full_name, content_hash
            FROM files
            WHERE {predicate}
              AND content_hash IS NOT NULL
            GROUP BY repo_full_name, content_hash
            HAVING count(*) > 1
        )
        SELECT f.repo_full_name, f.content_hash, f.path, f.size_bytes,
               f.html_url
        FROM files AS f
        INNER JOIN duplicate_groups AS g
                ON g.repo_full_name = f.repo_full_name
               AND g.content_hash = f.content_hash
        WHERE {aliased}
        ORDER BY lower(f.repo_full_name), f.repo_full_name, f.content_hash,
                 lower(f.path), f.path
    """


def _representative_content_query() -> str:
    predicate = _exact_predicate()
    aliased = _exact_predicate(alias="f")
    return f"""
        WITH duplicate_groups AS (
            SELECT repo_full_name, content_hash
            FROM files
            WHERE {predicate}
              AND content_hash IS NOT NULL
            GROUP BY repo_full_name, content_hash
            HAVING count(*) > 1
        ), duplicate_hashes AS (
            SELECT DISTINCT content_hash FROM duplicate_groups
        ), representative_ids AS (
            SELECT f.content_hash, min(f.id) AS file_id
            FROM files AS f
            INNER JOIN duplicate_hashes AS h
                    ON h.content_hash = f.content_hash
            WHERE {aliased}
            GROUP BY f.content_hash
        )
        SELECT f.content_hash, f.size_bytes, f.content
        FROM files AS f
        INNER JOIN representative_ids AS r ON r.file_id = f.id
        ORDER BY f.content_hash
    """


def _stable_audit_key(seed: int, content_hash: str) -> str:
    return hashlib.sha256(f"{seed}:{content_hash}".encode()).hexdigest()


def select_audit_rows(
    contents: Sequence[ContentClassRow],
    full_content: dict[str, str],
    *,
    per_category: int,
    seed: int,
) -> list[AuditRow]:
    """Select category-by-size stratified content identities deterministically."""
    selected: list[ContentClassRow] = []
    band_order = ("<=50", "51-200", "201-1000", "1001-5000", ">5000", "unknown")
    for category in CATEGORIES:
        candidates = [item for item in contents if item.primary_category == category]
        queues: dict[str, list[ContentClassRow]] = {}
        for band in band_order:
            queues[band] = sorted(
                [item for item in candidates if _size_band(item.size_bytes) == band],
                key=lambda item: _stable_audit_key(seed, item.content_hash),
            )
        chosen: list[ContentClassRow] = []
        while len(chosen) < per_category:
            progressed = False
            for band in band_order:
                if queues[band] and len(chosen) < per_category:
                    chosen.append(queues[band].pop(0))
                    progressed = True
            if not progressed:
                break
        selected.extend(chosen)

    rows: list[AuditRow] = []
    for index, item in enumerate(selected, 1):
        rows.append(
            AuditRow(
                audit_id=f"RC{index:03d}",
                category_stratum=item.primary_category,
                size_band=_size_band(item.size_bytes),
                content_hash=item.content_hash,
                repository_groups=item.repository_groups,
                files=item.files,
                repeated_instances=item.repeated_instances,
                size_bytes=item.size_bytes,
                representative_repo=item.representative_repo,
                representative_path=item.representative_path,
                auto_category=item.primary_category,
                auto_subtype=item.subtype,
                auto_confidence=item.confidence,
                rule_id=item.rule_id,
                target_basenames=item.target_basenames,
                evidence=item.evidence,
                content_excerpt=_excerpt(full_content[item.content_hash], 2500),
            )
        )
    return rows


def _category_summary(
    content_rows: Sequence[ContentClassRow],
    group_rows: Sequence[GroupRow],
) -> list[dict[str, int | float | str]]:
    total_contents = len(content_rows)
    total_groups = len(group_rows)
    total_files = sum(row.copies for row in group_rows)
    total_repeated = sum(row.repeated_instances for row in group_rows)
    output: list[dict[str, int | float | str]] = []
    for category in CATEGORIES:
        contents = [row for row in content_rows if row.primary_category == category]
        groups = [row for row in group_rows if row.primary_category == category]
        files = sum(row.copies for row in groups)
        repeated = sum(row.repeated_instances for row in groups)
        repositories = len({row.repo_full_name for row in groups})
        output.append(
            {
                "category": category,
                "unique_contents": len(contents),
                "unique_content_share": _share(len(contents), total_contents),
                "repository_groups": len(groups),
                "repository_group_share": _share(len(groups), total_groups),
                "repositories": repositories,
                "files": files,
                "file_share": _share(files, total_files),
                "repeated_instances": repeated,
                "repeated_instance_share": _share(repeated, total_repeated),
            }
        )
    return output


def analyze_repeated_content(
    db_path: str | Path,
    *,
    config: ClassifierConfig = ClassifierConfig(),
    audit_per_category: int = 10,
    audit_seed: int = 20260727,
) -> tuple[
    dict[str, object],
    list[ContentClassRow],
    list[GroupRow],
    list[MemberRow],
    list[AuditRow],
]:
    """Classify exact content repeated within repositories."""
    for name, value in asdict(config).items():
        if value <= 0:
            raise ValueError(f"{name} must be positive")
    if audit_per_category <= 0:
        raise ValueError("audit_per_category must be positive")

    connection = _readonly_connection(db_path)
    try:
        grouped_members: dict[tuple[str, str], list[DuplicateMember]] = defaultdict(list)
        for row in connection.execute(_group_query()):
            member = DuplicateMember(
                repo_full_name=str(row["repo_full_name"]),
                content_hash=str(row["content_hash"]),
                path=str(row["path"]),
                size_bytes=(
                    int(row["size_bytes"])
                    if row["size_bytes"] is not None
                    else None
                ),
                html_url=row["html_url"],
            )
            grouped_members[(member.repo_full_name, member.content_hash)].append(member)

        contents: dict[str, str] = {}
        sizes: dict[str, int | None] = {}
        for row in connection.execute(_representative_content_query()):
            content_hash = str(row["content_hash"])
            contents[content_hash] = str(row["content"] or "")
            sizes[content_hash] = (
                int(row["size_bytes"])
                if row["size_bytes"] is not None
                else None
            )
    finally:
        connection.close()

    classifications = {
        content_hash: classify_content(
            content_hash,
            content,
            sizes.get(content_hash),
            config=config,
        )
        for content_hash, content in contents.items()
    }

    groups_by_hash: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for key in grouped_members:
        groups_by_hash[key[1]].append(key)

    content_rows: list[ContentClassRow] = []
    for content_hash in sorted(classifications):
        classification = classifications[content_hash]
        group_keys = groups_by_hash[content_hash]
        members = [member for key in group_keys for member in grouped_members[key]]
        members.sort(
            key=lambda member: (
                member.repo_full_name.casefold(),
                member.repo_full_name,
                member.path.casefold(),
                member.path,
            )
        )
        content_rows.append(
            ContentClassRow(
                content_hash=content_hash,
                repository_groups=len(group_keys),
                repositories=len({key[0] for key in group_keys}),
                files=len(members),
                repeated_instances=sum(
                    len(grouped_members[key]) - 1 for key in group_keys
                ),
                size_bytes=classification.size_bytes,
                line_count=classification.line_count,
                nonempty_line_count=classification.nonempty_line_count,
                word_count=classification.word_count,
                heading_count=classification.heading_count,
                reference_count=classification.reference_count,
                direct_include_count=classification.direct_include_count,
                primary_category=classification.primary_category,
                subtype=classification.subtype,
                confidence=classification.confidence,
                rule_id=classification.rule_id,
                target_category=classification.target_category,
                target_basenames=classification.target_basenames,
                target_paths=classification.target_paths,
                representative_repo=members[0].repo_full_name,
                representative_path=members[0].path,
                evidence=classification.evidence,
                content_excerpt=classification.content_excerpt,
            )
        )

    group_rows: list[GroupRow] = []
    member_rows: list[MemberRow] = []
    for key in sorted(
        grouped_members,
        key=lambda item: (item[0].casefold(), item[0], item[1]),
    ):
        repo_full_name, content_hash = key
        members = sorted(
            grouped_members[key],
            key=lambda member: (member.path.casefold(), member.path),
        )
        classification = classifications[content_hash]
        context_tags = _path_context_tags(member.path for member in members)
        group_rows.append(
            GroupRow(
                repo_full_name=repo_full_name,
                content_hash=content_hash,
                copies=len(members),
                repeated_instances=len(members) - 1,
                size_bytes=classification.size_bytes,
                primary_category=classification.primary_category,
                subtype=classification.subtype,
                confidence=classification.confidence,
                rule_id=classification.rule_id,
                target_category=classification.target_category,
                target_basenames=classification.target_basenames,
                target_paths=classification.target_paths,
                path_context_tags=context_tags,
                representative_path=members[0].path,
                evidence=classification.evidence,
            )
        )
        for member in members:
            member_rows.append(
                MemberRow(
                    repo_full_name=repo_full_name,
                    content_hash=content_hash,
                    group_copies=len(members),
                    group_repeated_instances=len(members) - 1,
                    primary_category=classification.primary_category,
                    subtype=classification.subtype,
                    path_context_tags=context_tags,
                    path=member.path,
                    size_bytes=member.size_bytes,
                    html_url=member.html_url,
                )
            )

    category_rows = _category_summary(content_rows, group_rows)
    audit_rows = select_audit_rows(
        content_rows,
        contents,
        per_category=audit_per_category,
        seed=audit_seed,
    )

    pointer_contents = [
        row for row in content_rows if row.primary_category == "pointer_shim"
    ]
    pointer_groups = [
        row for row in group_rows if row.primary_category == "pointer_shim"
    ]
    target_categories = sorted(
        {row.target_category for row in pointer_contents}
    )
    summary: dict[str, object] = {
        "analysis": "automatic form classification of repository-local exact CLAUDE.md reuse",
        "scope": "exact-claude within-repository content hashes with two or more paths",
        "classifier_version": "phase1b-v1",
        "parameters": {
            **asdict(config),
            "audit_per_category": audit_per_category,
            "audit_seed": audit_seed,
        },
        "definitions": {
            "classification_unit": "unique SHA-256 content hash classified once",
            "repository_group": "one (repo_full_name, content_hash) with at least two exact CLAUDE.md paths",
            "repeated_instance": "group copies minus one",
            "pointer_shim": "short reference-only or reference-directed document under an explicit residual-word rule",
            "empty_placeholder": "no substantive characters after generic title/comments, an empty paired tag block, or a recognized placeholder phrase",
            "generated_context": "explicit generated/context marker within the first 1,500 characters",
            "template_scaffold": "explicit self-description as a template, scaffold, starter, or clone-and-customize document within the first 2,000 characters",
            "substantive_repeated_document": "meets at least one configured word, non-empty-line, or byte threshold after higher-priority rules",
            "short_ambiguous": "does not meet a higher-precision form rule",
            "path_context_tags": "secondary lexical tags from directory-component names; not intent classifications",
        },
        "population": {
            "unique_contents": len(content_rows),
            "repository_groups": len(group_rows),
            "repositories": len({row.repo_full_name for row in group_rows}),
            "files": len(member_rows),
            "repeated_instances": sum(row.repeated_instances for row in group_rows),
            "audit_rows": len(audit_rows),
        },
        "categories": category_rows,
        "confidence": [
            {
                "confidence": confidence,
                "unique_contents": count,
                "unique_content_share": _share(count, len(content_rows)),
            }
            for confidence, count in sorted(
                Counter(row.confidence for row in content_rows).items()
            )
        ],
        "size_bands": [
            {
                "size_band": band,
                "unique_contents": count,
                "unique_content_share": _share(count, len(content_rows)),
            }
            for band, count in sorted(
                Counter(_size_band(row.size_bytes) for row in content_rows).items(),
                key=lambda item: ("<=50", "51-200", "201-1000", "1001-5000", ">5000", "unknown").index(item[0]),
            )
        ],
        "pointer_targets": [
            {
                "target_category": target,
                "unique_contents": sum(
                    row.target_category == target for row in pointer_contents
                ),
                "repository_groups": sum(
                    row.target_category == target for row in pointer_groups
                ),
                "files": sum(
                    row.copies
                    for row in pointer_groups
                    if row.target_category == target
                ),
                "repeated_instances": sum(
                    row.repeated_instances
                    for row in pointer_groups
                    if row.target_category == target
                ),
            }
            for target in target_categories
        ],
        "path_context_tags": [
            {
                "tag": tag,
                "repository_groups": sum(
                    tag in row.path_context_tags.split(";") for row in group_rows
                ),
                "files": sum(
                    row.copies
                    for row in group_rows
                    if tag in row.path_context_tags.split(";")
                ),
            }
            for tag in PATH_CONTEXT_MARKERS
        ],
        "largest_groups_by_category": {
            category: [
                {
                    "repo_full_name": row.repo_full_name,
                    "copies": row.copies,
                    "size_bytes": row.size_bytes,
                    "subtype": row.subtype,
                    "representative_path": row.representative_path,
                    "evidence": row.evidence,
                }
                for row in sorted(
                    [item for item in group_rows if item.primary_category == category],
                    key=lambda item: (
                        -item.copies,
                        item.repo_full_name.casefold(),
                        item.repo_full_name,
                        item.content_hash,
                    ),
                )[:10]
            ]
            for category in CATEGORIES
        },
        "interpretation": (
            "automatic form labels with evidence-bearing deterministic rules; "
            "manual validation is required before semantic or prevalence claims"
        ),
    }
    return summary, content_rows, group_rows, member_rows, audit_rows


def _write_dataclass_csv(
    rows: Sequence[object],
    output_path: str | Path,
    fields: Sequence[str],
) -> Path:
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow(asdict(row))  # type: ignore[arg-type]
    return output


def write_classes_csv(rows: Sequence[ContentClassRow], output_path: str | Path) -> Path:
    return _write_dataclass_csv(rows, output_path, tuple(ContentClassRow.__dataclass_fields__))


def write_groups_csv(rows: Sequence[GroupRow], output_path: str | Path) -> Path:
    return _write_dataclass_csv(rows, output_path, tuple(GroupRow.__dataclass_fields__))


def write_members_csv(rows: Sequence[MemberRow], output_path: str | Path) -> Path:
    return _write_dataclass_csv(rows, output_path, tuple(MemberRow.__dataclass_fields__))


def write_audit_csv(rows: Sequence[AuditRow], output_path: str | Path) -> Path:
    return _write_dataclass_csv(rows, output_path, tuple(AuditRow.__dataclass_fields__))


def write_summary_json(summary: dict[str, object], output_path: str | Path) -> Path:
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return output


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Read mined.db without modifying it and classify exact CLAUDE.md "
            "content repeated within repositories."
        )
    )
    parser.add_argument("--db", default="mined.db", help="SQLite database")
    parser.add_argument(
        "--classes-output",
        default="claude_repeated_content_classes.csv",
        help="one-row-per-unique-content CSV",
    )
    parser.add_argument(
        "--groups-output",
        default="claude_repeated_content_groups.csv",
        help="one-row-per-repository-duplicate-group CSV",
    )
    parser.add_argument(
        "--members-output",
        default="claude_repeated_content_members.csv",
        help="one-row-per-participating-file CSV",
    )
    parser.add_argument(
        "--audit-output",
        default="claude_repeated_content_audit.csv",
        help="deterministic stratified audit CSV",
    )
    parser.add_argument(
        "--summary-output",
        default="claude_repeated_content_summary.json",
        help="machine-readable JSON summary",
    )
    parser.add_argument(
        "--pointer-max-residual-words",
        type=positive_int,
        default=60,
    )
    parser.add_argument("--substantive-min-words", type=positive_int, default=50)
    parser.add_argument(
        "--substantive-min-nonempty-lines",
        type=positive_int,
        default=8,
    )
    parser.add_argument("--substantive-min-bytes", type=positive_int, default=500)
    parser.add_argument("--audit-per-category", type=positive_int, default=10)
    parser.add_argument("--audit-seed", type=int, default=20260727)
    parser.add_argument("--top", type=positive_int, default=5)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    config = ClassifierConfig(
        pointer_max_residual_words=args.pointer_max_residual_words,
        substantive_min_words=args.substantive_min_words,
        substantive_min_nonempty_lines=args.substantive_min_nonempty_lines,
        substantive_min_bytes=args.substantive_min_bytes,
    )
    try:
        summary, classes, groups, members, audit = analyze_repeated_content(
            args.db,
            config=config,
            audit_per_category=args.audit_per_category,
            audit_seed=args.audit_seed,
        )
        classes_path = write_classes_csv(classes, args.classes_output)
        groups_path = write_groups_csv(groups, args.groups_output)
        members_path = write_members_csv(members, args.members_output)
        audit_path = write_audit_csv(audit, args.audit_output)
        summary_path = write_summary_json(summary, args.summary_output)
    except (FileNotFoundError, OSError, sqlite3.Error, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    population = summary["population"]
    assert isinstance(population, dict)
    print(
        f"Unique contents: {population['unique_contents']:,}; repository groups: "
        f"{population['repository_groups']:,}; files: {population['files']:,}"
    )
    print("Automatic primary categories:")
    category_rows = summary["categories"]
    assert isinstance(category_rows, list)
    for row in category_rows:
        assert isinstance(row, dict)
        print(
            f"  {row['category']:<31} "
            f"contents={row['unique_contents']:>4,}  "
            f"groups={row['repository_groups']:>4,}  files={row['files']:>5,}"
        )
    print("Largest groups by category:")
    largest = summary["largest_groups_by_category"]
    assert isinstance(largest, dict)
    for category in CATEGORIES:
        examples = largest[category]
        assert isinstance(examples, list)
        for item in examples[: args.top]:
            print(
                f"  {category:<31} {item['copies']:>4,}  "
                f"{item['repo_full_name']}::{item['representative_path']}"
            )
    print(f"Classes CSV: {classes_path.resolve()}")
    print(f"Groups CSV: {groups_path.resolve()}")
    print(f"Members CSV: {members_path.resolve()}")
    print(f"Audit CSV: {audit_path.resolve()}")
    print(f"Summary JSON: {summary_path.resolve()}")
    print("Database writes: 0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
